// ALERT
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

// AUTH LOGIN REGISTER
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

// PROFILE
export const GET_PROFILE = "GET_PROFILE";
export const GET_PROFILES = "GET_PROFILES";
export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const CLEAR_PROFILE = "CLEAR_PROFILE";
export const PROFILE_ERROR = "PROFILE_ERROR";
export const ACCOUNT_DELETED = "ACCOUNT_DELETED";
export const PROFILE_USER_LOADED = "PROFILE_USER_LOADED";
export const PROFILE_NOT_EXISTS = "PROFILE_NOT_EXISTS";
export const PROFILE_USER_SUCCESS = "PROFILE_USER_SUCCESS";
export const PROFILE_USER_FAIL = "PROFILE_USER_FAIL";
export const PROFILES_LOADED = "PROFILES_LOADED";
export const INITIATE_EDITING = "INITIATE_EDITING";
export const PROFILE_RECIEVE_NOTIFICATION = "PROFILE_RECIEVE_NOTIFICATION";

// POST AND COMMENT
export const GET_POSTS = "GET_POSTS";
export const GET_POST = "GET_POST";
export const POST_ERROR = "POST_ERROR";
export const UPDATE_LIKES = "UPDATE_LIKES";
export const DELETE_POST = "DELETE_POST";
export const ADD_POST = "ADD_POST";
export const ADD_COMMENT = "ADD_COMMENT";
export const REMOVE_COMMENT = "REMOVE_COMMENT";

// GROUPS
export const GROUPS_LOADED = "GROUPS_LOADED";
export const GROUPS_FAIL = "GROUPS_FAIL";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const CLEAR_PROMPTS = "CLEAR_PROMPTS";
export const CREATE_GROUP = "CREATE_GROUP";
export const GROUP_CREATE_FAIL = "GROUP_CREATE_FAIL";
export const CLEAR_SUCCESS = "CLEAR_SUCCESS";
export const GROUPS_CLEAR_FILTER = "GROUPS_CLEAR_FILTER";
export const GROUPS_FILTER_COURSE = "GROUPS_FILTER_COURSE";
export const GROUPS_CLEAR_SEARCH = "GROUPS_CLEAR_SEARCH";
export const GROUPS_FILTER_SEARCH = "GROUPS_FILTER_SEARCH";
export const GROUPS_SET_CURRENT = "GROUPS_SET_CURRENT";
export const GROUPS_USER_LOADED = "GROUPS_USER_LOADED";
export const SEND_JOIN_REQUEST = "SEND_JOIN_REQUEST";
export const GET_GROUP = "GET_GROUP";
export const GROUP_ERROR = "GROUP_ERROR";

// PEERS
export const PEERS_CLEAR_FILTER = "PEERS_CLEAR_FILTERs";
export const PEERS_CLEAR_SEARCH = "PEERS_CLEAR_SEARCHs";
export const PEERS_FAIL = "PEERS_FAIL";
export const PEERS_FILTER_COURSE = "PEERS_FILTER_COURSE";
export const PEERS_FILTER_SEARCH = "PEERS_FILTER_SEARCH";
export const PEERS_LOADED = "PEERS_LOADED";

// BUDDY REQUEST
export const BUDDY_REQUEST_SENT = "BUDDY_REQUEST_SENT";
export const CLEAR_NOTIFICATIONS = "CLEAR_NOTIFICATIONS";
export const GROUPS_FILTER_CURRENT = "GROUPS_FILTER_CURRENT";

//CATEGORIES
export const ADD_CATEGORY = "ADD_CATEGORY";
export const CATEGORY_ERROR = "CATEGORY_ERROR";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const GET_CATEGORIES = "GET_CATEGORIES";
export const GET_CATEGORY = "GET_CATEGORY";

//COURSE
export const ADD_COURSE = "ADD_COURSE";
export const GET_COURSE = "GET_COURSE";
export const COURSE_ERROR = "COURSE_ERROR";
export const COURSES_ERROR = "COURSES_ERROR";
export const DELETE_COURSE = "COURSE_ERROR";
export const GET_COURSES = "GET_COURSES";
export const GET_DEFAULT_PHOTO = "GET_DEFAULT_PHOTO";
export const ADD_LESSON = "ADD_LESSON";
export const LESSON_ERROR = "LESSON_ERROR";

//EVENT
export const GET_EVENT = "GET_EVENT";
export const GET_EVENTS = "GET_EVENTS";
export const GET_EVENTS_FAIL = "GET_EVENTS_FAIL";
export const UPDATE_EVENT = "UPDATE_EVENT";
export const ADD_EVENT = "ADD_EVENT";
export const EVENT_ERROR = "EVENT_ERROR";

//to do
export const GET_VIDEO = "GET_VIDEO";
export const GET_VIDEOS = "GET_VIDEOS";
export const VIDEO_ERROR = "VIDEO_ERROR";
